
server:
  port: 8c;081

# app properties
ramninder:
  app:
    jwtExpirationMs: '86400000'
    jwtSecret: ramninderSecretKey

spring:
  application:
    name: springSecurity

  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
      show-sql: true
  sql:
    init:
      mode: NEVER